### ISSUE TITLE
Missing Corresponding EN ids in lexicon

### ISSUE THREAD

**Issue by ghost** [rali-udem/SimpleNLG-EnFr#3]
In looking at the default French lexicon, I noticed this:

```
    <word>
        <base>abaisser</base>
        <category>verb</category>
        <id>abaisser_1</id>
    </word>
```

where I would have expected this

```
    <word>
        <base>abaisser</base>
        <category>verb</category>
        <id>E0038108</id>
    </word>
```

Is it correct to assume that the lexicon would be improved if this mapping was updated, or is there a reason why it hasn't been done for all verbs.

Should this mapping be updated in `default_french_lexicon.xml` or in a new lexicon?

**Comment by vaudrypl** [comment]
If you look in the French documentation on page 12, you will find this:

> La première entrée de l'exemple 2.1, l'article défini le, a été rédigée à la main et l'id correspond à celui de l'entrée du déterminant the du lexique XML anglais par défaut. La deuxième entrée de l'exemple 2.1 a été générée en partie automatiquement. En effet, les noms, adjectifs et adverbes de la liste de l'échelle orthographique Dubois Buyse, trouvée sur la page web de Bacquet, ont été complétés par les formes fléchies de Morphalou 2.0 (CNRTL) (voir p. 4). Quelques traits correspondant à ces formes fléchies sont pour cette raison redondants, car SimpleNLG-EnFr peut les calculer si elles sont relativement régulières (voir p. 15, 16 et 19). L'id des entrées dont les formes fléchies ont été tirées de Morphalou 2.0 provient également de celle-ci.

It means that for lexicon entries that were entered manually (a lot of them function words), I put the same ID than for what I judged was the corresponding entry in the English default XML lexicon. (Originally those IDs come from the _NIH Specialist lexicon_.) An example is the French determiner _le_, to which I assigned the ID **E0060487**, the same as for the English determiner _the_. For entries that were entered automatically or semi-automatically, the ID comes from the corresponding entry in the Morphalou 2.0 lexicon, from which the French morphological forms were extracted. An example would be **abaisser_1**.

You could try to match more IDs in the French default XML lexicon with entries in the English XML default lexicon, but that would be non trivial and somewhat arbitrary because of ambiguity and synonymy problems inherent in translation.
